version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    networks:
      - kafka

  kafka:
    image: wurstmeister/kafka:0.10.1.1
    hostname: kafka
    networks:
      - kafka
      - kafka-matcher
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  topic-producer:
    image: wurstmeister/kafka:0.10.1.1
    networks:
      - kafka
    command: "bash -c 'for i in `seq 1 100`;
                       do
                         echo \"{\\\"value\\\":$$i}\" | /opt/kafka/bin/kafka-console-producer.sh --broker-list kafka:9092 --topic sourceTopic;
                         echo $$i;
                       done'"
    depends_on:
      - kafka

  rules:
    image: clue/json-server
    volumes:
      - ./mockRules/rules.json:/data/db.json
    networks:
      - kafka-matcher

  kafka-transform:
    image: socialmetrix/kafka-transform
    environment:
      - JsonTemplateService.url=http://template
      - RulesService.url=http://rules/rules
      - kafka.application.id=kafka-transform
      - kafka.bootstrap.servers=kafka:9092
      - kafka.topic.source=sourceTopic
      - kafka.topic.sink=sinkTopic
    networks:
      - kafka-matcher
    depends_on:
      - kafka
      - template

networks:
  kafka:
  kafka-matcher: